config/routes.rb
CampusgeniUs::Application.routes.draw do

  match '/dashboard' => 'dashboards#show', as: 'dashboard'

  authenticated :user do
    root :to => 'dashboards#show'
  end

  root :to => "home#index"

  devise_for :users

  resources :users do
    resources :books
  end

  resource :dashboard, only: [:show]
  resources :sections
  resources :courses

  match 'search' => 'books#search', :as => 'book_search', :via => :get
  match 'site_search' => 'books#site_search', :as => 'site_search', via: :get
  match 'books' => 'books#all_books', via: :get
  match 'books' => 'books#make_user_login', via: :post
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="hero-unit text-center">
  <%= image_tag "logo.jpg", size: "150x150", class: "main-logo" %>
  <h1> add book </h1>
  <%= form_tag book_search_path, :method => "get", :class => "form-search" do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], :class => "span4 search-query", :placeholder => "Search a 10 digit ISBN" %>
      <%= button_tag "Add a Book", :name => nil, :class => "btn" %>
    </div>
  <% end %>
</div>

<div class="hero-unit text-center">
  <h1> site search </h1>

  <%= form_tag site_search_path, :method => "get", :class => "form-search" do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], :class => "span4 search-query", :placeholder => "Search a title or ISBN" %>
      <%= button_tag "Search For Book", :name => nil, :class => "btn" %>
    </div>
  <% end %>
</div>