config/routes.rb
CampusgeniUs::Application.routes.draw do

  match '/dashboard' => 'dashboards#show', as: 'dashboard'

  authenticated :user do
    root :to => 'dashboards#show'
  end

  root :to => "home#index"

  devise_for :users

  resources :users do
    resources :books
  end

  resource :dashboard, only: [:show]
  resources :sections
  resources :courses

  match 'search' => 'books#search', :as => 'book_search', :via => :get
  match 'site_search' => 'books#site_search', :as => 'site_search', via: :get
  match 'books' => 'books#all_books', via: :get
  match 'books' => 'books#make_user_login', via: :post
end

app/models/book.rb
class Book < ActiveRecord::Base

  attr_accessible :author, :course_id, :isbn, :title, :user_id, :course_id, :amazon_url,
  				  :small_image_url, :medium_image_url, :large_image_url, :publisher,
  				  :edition, :number_of_pages, :days

  # validates :author, :isbn, :title, :amazon_url, :small_image_url, :medium_image_url, :large_image_url,
  # 			:publisher, :number_of_pages, :days, presence: true
  validates :days, inclusion: 1..7

  belongs_to :user
  has_and_belongs_to_many :courses
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'yaml' #for when i extract
  require 'vacuum'

  before_filter :authenticate_user!, only: [:create, :make_user_login]

  def index
  	user = User.find(params[:user_id])
  	@books = user.books.find(:all)
  end

  def show
    user = current_user
    @book = Book.find(params[:id])

  end

  def create
    if current_user.books.build(params[:book]).save
	  redirect_to dashboard_path, notice: "added book"
	else
	  redirect_to :back, notice: "shit didn't work son <%= p #{params[:book]}"
    end
  end

  def search
  	isbn_query = params.fetch(:search, '')
  	strip_hyphen!(isbn_query)

  	unless (isbn_query.size == 10 || isbn_query.size == 13)
  		flash[:notice] = "10/13 Digit ISBN Please."
  		redirect_to root_url
  		return
  	end

  	@user = current_user
  	@book = AmazonSearch.new("#{isbn_query}").amazon_request

  	if @user
  		@path = [@user, @book]
  	else
  		@path = @book
  	end
  end

  def all_books
	  @books = Book.all
  end

  def site_search
    site_query = params.fetch(:search, '')
    @books = Book.where("title like ? OR isbn like ?", "%#{site_query}%", "%#{site_query}%")
  end

  def make_user_login
  end

  private

  def strip_hyphen!(string)
	 string.gsub!("-", "")
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/all_books.html.erb
<div class="row">
	<div class="span6 offset3">
	  <ul>
	    <% @books.each do |book| %>
	    <div class="book-listing">
		  <div class="book-listing-image">
	        <li> <%= link_to(image_tag("#{book.medium_image_url}"), book.amazon_url) %> </li>
	      </div>
	      <div class="book-listing-info">
	        <p> Title: <%= book.title %> </p>
	        <p> ISBN: <%= book.isbn %></p>
	        <p> Author: <%= book.author %> </p>
	        <p> Pages: <%= book.number_of_pages %> </p>
	      </div>
	    </div>
	    <div class="clearfix"></div>
	    <% end %>
	  </ul>
	</div>
</div>

app/views/books/create.html.erb
<h1> created! </h1>
<%= pp @book %>

app/views/books/index.html.erb
<h1> Listing Books for User: <%= current_user.email %> </h1>
<ul>
  <%= @books.each do |book| %>
  <li> <%= book.title %> </li>
  <% end %>
</ul>

app/views/books/search.html.erb
<div class="row">

	<div class="span6">
	  <%= link_to(image_tag("#{@book.large_image_url}"), @book.amazon_url) %>
	</div>

	<div class="span6"
		<div id="book-form">
			<%= form_for @path, html: {class: "form-horizontal"} do |f| %>

				<%= f.label :title %>
				<%= f.text_field :title, readonly: true %>

				<%= f.label :author %>
				<%= f.text_field :author, readonly: true %>

				<%= f.label :title %>
				<%= f.text_field :title, readonly: true %>

				<%= f.label :edition %>
				<%= f.text_field :edition, readonly: true %>

				<%= f.label :days, "How many days/week do you need the book?" %>
				<%= f.select :days, (1..7) %>

				<%= f.hidden_field :number_of_pages %>
				<%= f.hidden_field :large_image_url %>
				<%= f.hidden_field :small_image_url %>
				<%= f.hidden_field :medium_image_url %>
				<%= f.hidden_field :amazon_url %>
				<%= f.hidden_field :publisher %>
				<%= f.hidden_field :isbn %>

				<div class="clearfix"></div>

				<%= f.submit "Add My Book", class: 'btn add-book' %>
			<% end %>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<h1> Viewing Book </h1>

<h2> Owner: <%= @book.user.name %> </h2>
<h2> Title: <%= @book.title %> </h2>
<h2> Author: <%= @book.author %></h2>

app/views/books/site_search.html.erb
<h1> site search </h1>
<p>
  <% @books.each do |book| %>
  <div class="site-search-result">
    <h3><%= link_to "#{book.title}", user_book_path(book.user, book) %> </h3>
    <h3><%= book.isbn %> </h3>
    <h3><%= book.author %> </h3>
    <h3><%= book.user.name %></h3>
  </div>
  <% end %>
</p>